[project]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = [
    {name = "Juliana",email = "julianacarvajalguerra@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
  { include = "gendiff" },
]

[tool.poetry.scripts]
gendiff = "gendiff.scripts.gendiff:main"

[dependency-groups]
dev = [
    "ruff (>=0.15.10,<0.16.0)"
]
