name: Quality and tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  run-makefile-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run Linter via Makefile
        run: make lint
        
#   test-and-quality:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.13"

#       # 2. Instalar el CLI de Qlty en el runner
#       - name: Install Qlty CLI
#         uses: qltysh/qlty-action/install@v2

#       # 3. Formatear y analizar la salud del código
#       - name: Check format and quality
#         run: |
#           qlty fmt --check
#           qlty check

#       - name: Install Poetry
#         run: pipx install poetry

#       - name: Install dependencies
#         run: poetry install

#       - name: Ejecutar Pruebas
#         run: poetry run pytest